name: compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install packages
      run: sudo apt-get install -y --no-install-recommends --no-install-suggests
           meson ninja-build
           libevdev-dev liburing-dev
           libwayland-dev libwayland-client0 wayland-protocols 

    - name: configure
      run: CFLAGS='-O3 -pipe' meson setup build --buildtype release

    - name: compile
      run: ninja -C build

    - name: release
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ startsWith(github.event.head_commit.message, 'release:') }}
      continue-on-error: true
      run: |
        strip build/gamepad_idle_inhibit

        version=$(echo ${{ github.event.head_commit.message }} | tr ' ' '\n' | tail -n 1)
        file=build/gamepad_idle_inhibit

        echo **Workflow run**: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID >> notes

        gh release create $version --notes-file notes $file
