name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install packages
      run: sudo apt-get install -y --no-install-recommends --no-install-suggests
           meson ninja-build
           liburing-dev
           libwayland-dev libwayland-client0 wayland-protocols 

    - name: configure
      run: meson setup build --buildtype release -Dtest=true

    - name: test
      run: meson test -C build
